In [1]:
import numpy as np

In [26]:
def activation(z):
    return  1/(1 + np.exp(-z))

def activation_derivative(x):
    return x * (1 - x)

training_inputs = np.array([[0, 0, 1],
                           [1, 1, 1],
                           [1, 0, 1],
                           [0, 1, 1]])

training_outputs = np.array([[0, 1, 1, 0]]).T

np.random.seed(1)

random_weights = 2 * np.random.random((3, 1)) - 1

print(random_weights)

for i in range(20000):
    input_layer = training_inputs
    outputs = activation(np.dot(input_layer, random_weights))
    
    error = training_outputs - outputs
    adjustments = error * activation_derivative(outputs)
    random_weights += np.dot(input_layer.T, adjustments)
    
print("Actual Out \n", training_outputs)
print("Network Out \n", outputs)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Actual Out 
 [[0]
 [1]
 [1]
 [0]]
Network Out 
 [[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]
